<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: mezka
 * Date: Fri, 27 Apr 2018 11:58:05 -0400
 */

$conf['title'] = 'MesquitaWiki';
$conf['start'] = 'home';
$conf['lang'] = 'es';
$conf['htmlok'] = 1;
$conf['plugin']['authmysql']['TablesToLock'] = array();

// end auto-generated content
